version: "3.8"

services:
  execution:
    image: ethpandaops/erigon:2.53.0
    user: "root"
    command:
      --log.console.verbosity=3
      --datadir=/execution-data
      --port=50803
      --networkid=28256
      --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin,ots
      --http.vhosts=*
      --ws
      --allow-insecure-unlock
      --nat=extip:${IP_ADDRESS}
      --http
      --http.addr=0.0.0.0
      --http.corsdomain=*
      --http.port=8545
      --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts=*
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=9001
      --bootnodes=enode://30674d1f5fa3cf763c2d991eeaf585db42c45737a4d47aee3653b50ac33947437769e13f04c12bab63d5c2a416d08b2637e6340d13b7d59489f0ac8dae919756@88.99.94.109:50303
      --staticpeers=enode://30674d1f5fa3cf763c2d991eeaf585db42c45737a4d47aee3653b50ac33947437769e13f04c12bab63d5c2a416d08b2637e6340d13b7d59489f0ac8dae919756@88.99.94.109:50303
    volumes:
      - ./execution-data:/execution-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "10845:8545" 
      - "10846:8546" 
      - "10851:8551" 
      - "11301:9001" 
      - "50803:50803"
    restart: unless-stopped

  beacon:
    image: chainsafe/lodestar:latest
    command:
      - beacon 
      - --logLevel=info
      - --port=11300
      - --discoveryPort=11300
      - --dataDir=/consensus-data
      - --paramsFile=/el-cl-genesis-data/custom_config_data/config.yaml
      - --genesisStateFile=/el-cl-genesis-data/custom_config_data/genesis.ssz
      - --eth1.depositContractDeployBlock=0
      - --network.connectToDiscv5Bootnodes=true
      - --discv5=true
      - --eth1=true
      - --eth1.providerUrls=http://execution:8545
      - --execution.urls=http://execution:8551
      - --rest=true
      - --rest.address=0.0.0.0
      - --rest.namespace=*
      - --rest.port=4000
      - --nat=true
      - --enr.ip=${IP_ADDRESS}
      - --enr.tcp=11300
      - --enr.udp=11300
      - --subscribeAllSubnets=true
      - --jwt-secret=/el-cl-genesis-data/jwt/jwtsecret
      - --metrics
      - --metrics.address=0.0.0.0
      - --metrics.port=8008
      - --bootnodes=/ip4/88.99.94.109/tcp/11000/p2p/16Uiu2HAm4GXc2aYZkdfHvvn56s6zEdoSAwdiNcGkzvXX5y4MX4U4
    volumes:
      - ./consensus-data:/consensus-data 
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "11300:11300/tcp"
      - "11300:11300/udp"
      - "4500:4000"
      - "7454:8008"
    depends_on:
      - execution
    restart: unless-stopped


  validator:
    image: chainsafe/lodestar:latest
    user: "root"
    command:
      - validator
      - --logLevel=info 
      - --dataDir=/consensus-data/validator 
      - --paramsFile=/el-cl-genesis-data/custom_config_data/config.yaml 
      - --beaconNodes=http://beacon:4000 
      - --keystoresDir=/validator-keys/node-3-keystores/keys 
      - --secretsDir=/validator-keys/node-3-keystores/secrets 
      - --suggestedFeeRecipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776 
      - --metrics 
      - --metrics.address=0.0.0.0 
      - --metrics.port=8008
    volumes:
      - ./el-cl-genesis-data:/el-cl-genesis-data
      - ./validator-keys:/validator-keys
    ports:
      - "8242:5042"
      - "8264:8008"
    depends_on:
      - beacon
    restart: unless-stopped
